# Generated by Django 3.2.7 on 2021-11-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Perfil2',
        ),
    ]
