# Generated by Django 3.2.7 on 2022-05-06 17:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('LGBT', 'LGBT')], max_length=7, null=True)),
                ('img', models.ImageField(blank=True, max_length=250, null=True, upload_to='perfil/')),
                ('tipoUser', models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='Participante', max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
