# Generated by Django 3.2.7 on 2022-05-09 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('LGBT', 'LGBT')], max_length=7, null=True)),
                ('img', models.ImageField(blank=True, max_length=250, null=True, upload_to='users/')),
                ('tipoUser', models.CharField(choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='Participante', max_length=13)),
                ('carreraUniversitaria', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroDeHijos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=30, null=True)),
                ('etnia', models.CharField(blank=True, max_length=30, null=True)),
                ('estudiosPrevios', models.CharField(blank=True, max_length=100, null=True)),
                ('nivelDeFormacion', models.CharField(blank=True, max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Django Admin')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEvaluador', models.CharField(default='hTPsbz', max_length=6)),
                ('aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado')], default='pendiente', max_length=13)),
                ('razon', models.TextField(blank=True, default='La cuenta aún está en revisión, espere la aprobación del administrador.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEstudiante', models.CharField(default='Vti8J6', max_length=6)),
                ('aceptacionResponsable', models.CharField(default='sin_asignar', max_length=100)),
                ('razon', models.TextField(blank=True, default='No ha elegido ningún responsable evaluador.', null=True)),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participante_evaluador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='evaluador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_evaluador', to='usuario.evaluador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='participante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_participante', to='usuario.participante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
