# Generated by Django 3.2.7 on 2022-05-09 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='evaluador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='participante',
        ),
        migrations.AddField(
            model_name='evaluador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_participante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='codigoEvaluador',
            field=models.CharField(default='bEUTCJ', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigoEstudiante',
            field=models.CharField(default='3C4Fi7', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participante_evaluador', to='usuario.evaluador'),
        ),
    ]
