# Generated by Django 3.2.7 on 2022-05-06 22:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220506_1652'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUser',
            field=models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='Participante', max_length=13, null=True),
        ),
    ]
