# Generated by Django 3.2.7 on 2022-05-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_auto_20220513_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='codigoEvaluador',
            field=models.CharField(default='3Tq6de', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigoEstudiante',
            field=models.CharField(default='4K85E3', max_length=6),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUser',
            field=models.CharField(choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='participante', max_length=13),
        ),
    ]
