# Generated by Django 3.2.7 on 2022-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0024_auto_20220514_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='codigoEvaluador',
            field=models.CharField(default='Rpfm46', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='aceptacionResponsable',
            field=models.CharField(choices=[('sin_asignar', 'Sin Asignar'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado')], default='sin_asignar', max_length=13),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigoEstudiante',
            field=models.CharField(default='3ZYKUe', max_length=6),
        ),
    ]
