# Generated by Django 3.2.7 on 2022-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_auto_20220517_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='DQZFoi4tWQbfAGiTvPYPTjAZkDrAzvtJxmy69rBQZcYmkcDux7TXAdrKMhFkN5YG', max_length=64),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='codigoEvaluador',
            field=models.CharField(default='4DkrQW', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigoEstudiante',
            field=models.CharField(default='44hF8V', max_length=6),
        ),
    ]
