# Generated by Django 3.2.7 on 2022-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_auto_20220518_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='codigoEvaluador',
            field=models.CharField(default='47uVYe', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigoEstudiante',
            field=models.CharField(default='3fcjSN', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='5TDQcdvhtz8vyhhwyoDTaVXm9vcZBWTJAWdoMHNcBivDtMyBh8Wt6bZ3CnVBMT4T', max_length=64),
        ),
    ]
