# Generated by Django 3.2.7 on 2022-05-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_auto_20220518_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluador',
            name='codigoEvaluador',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='codigoEstudiante',
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='3HeQ8F', max_length=6),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='fyNSNpcGU5ahVZhvTuKRG93iCYDzFydV44jNxzLMAQuqFAKzDVKH6NNGZWLwSi3k', max_length=64),
        ),
    ]
