# Generated by Django 3.2.7 on 2022-05-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0030_auto_20220518_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='82RXTcDokRHuFP7xhVLNooS8XcmU3EC6weHJNwksggpRyKSJPHPzxgMF8PTjegwX', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='3B82No', max_length=6),
        ),
    ]
