# Generated by Django 3.2.7 on 2022-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0031_auto_20220518_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='CwxnTYLSguXRD7iLxq9PV8AsngS2FnLee2mbQCDcd4LbNFQDDdotakJGAv8bCBNA', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='4PvGM4', max_length=6),
        ),
    ]
