# Generated by Django 3.2.7 on 2022-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0032_auto_20220520_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='MELhiqZJ3vVAdty3uXSdCwfAjiZ36mgtiGdHKUv8MpjnmSwKjvMkQ6LE7MCvPYU9', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='fK8otn', max_length=6),
        ),
    ]
