# Generated by Django 3.2.7 on 2022-05-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0034_auto_20220522_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='MYECkaSFtEvgbLppKBxbgo47GQZbrX8Jhav2HXeLSjjNbutewdQd8vtm7nkqKsSM', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='49kycy', max_length=6),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
