# Generated by Django 3.2.7 on 2022-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0035_auto_20220523_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='FHYibvXUr34ftneYWq9N86KWXkRE63ADbALq2q7d99PvZCnv7NcvAhVpzGjV7h9M', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='4V8KeX', max_length=6),
        ),
    ]
