# Generated by Django 3.2.7 on 2022-05-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0035_auto_20220523_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='LCetLdUoQZsqhTigvNK8Lznx8LyPQoKp8YsWhW2yfpFvyu3dVGUYXpQvoZMhCjsR', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='JKoVuM', max_length=6),
        ),
    ]
