# Generated by Django 3.2.7 on 2022-06-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0036_auto_20220523_2222'),
        ('usuario', '0036_auto_20220523_2321'),
    ]

    operations = [
    ]
