# Generated by Django 3.2.7 on 2022-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0037_merge_0036_auto_20220523_2222_0036_auto_20220523_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='3xf3H23WS6sXMM8NhcJeaeyQ7W83khiRXhDtYoEzvZAshW9LXpWAaLTghZodatSu', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='RVn8AZ', max_length=6),
        ),
    ]
