# Generated by Django 3.2.7 on 2022-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0038_auto_20220603_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='EnuNmtEucAKhejCjabb4BSEBW74CwbjTpDPGyG3EUJtrQbRQk8ynK79sMdNiESLh', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='UJ32Nv', max_length=6),
        ),
    ]
