# Generated by Django 3.2.7 on 2022-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0038_auto_20220603_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='u9HFvvvBTojfbctSLjZpWFUiUnzp7gPCs5LYFo8FFxi3UUhaMtjC7B3zzASWNzTg', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='49ZsLV', max_length=6),
        ),
    ]
