# Generated by Django 3.2.7 on 2022-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0039_auto_20220603_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='certificado',
        ),
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='sdxYvS2BmXxn59EyubTUsCJoigxeBWfLZ3CWVTwrDKsWYWD8WtkyquMR5iJPdY4B', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='43ZSTp', max_length=6),
        ),
    ]
