# Generated by Django 3.2.7 on 2022-06-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0039_auto_20220606_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='sqtivCEtvmsekp57KJsLk9kJF5EcYymYyrE67Xf7RL3fkR2kqXqqDcRkhTZgK28a', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='tcG4D6', max_length=6),
        ),
    ]
