# Generated by Django 3.2.7 on 2022-06-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0040_auto_20220606_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='CWdtHRxDTzthAHbaX6afFVdJXRRDQmUSwSwBSUudHivkfmvZBeeSHtB8LZRmKnQT', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='3rWa79', max_length=6),
        ),
    ]
