# Generated by Django 3.2.7 on 2022-06-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0041_auto_20220606_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='ETHdooVR8RdtJu7qrfWynPyDzyTmoiRM3jYFQPVWWnhuesmQQap7XgTkh42xHk3v', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='3fRrqh', max_length=6),
        ),
    ]
