# Generated by Django 3.2.7 on 2022-06-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0039_auto_20220606_0029'),
        ('usuario', '0041_auto_20220605_1922'),
    ]

    operations = [
    ]
