# Generated by Django 3.2.7 on 2022-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0042_merge_0039_auto_20220606_0029_0041_auto_20220605_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='NoGmhonn5DSW768rpwv6MhRrMxyafQXPNayQmZe6hixSkxEHqQuf3gsP8sRPgJQ8', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='3EfTvV', max_length=6),
        ),
    ]
