# Generated by Django 3.2.7 on 2022-06-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0042_auto_20220606_2219'),
        ('usuario', '0042_merge_0039_auto_20220606_0029_0041_auto_20220605_1922'),
    ]

    operations = [
    ]
