# Generated by Django 3.2.7 on 2022-06-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0042_merge_0039_auto_20220606_0029_0041_auto_20220605_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='CJB8M3vMaK5wBC4vGXAMB3ZMMBQtbrV53h8cAnMPHeH6U8Pcsxc8JJ7bzgE23UdA', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='8FWQX9', max_length=6),
        ),
    ]
