# Generated by Django 3.2.7 on 2022-06-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0043_auto_20220608_1159'),
        ('usuario', '0043_merge_20220608_1207'),
    ]

    operations = [
    ]
