# Generated by Django 3.2.7 on 2022-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0044_merge_20220610_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='75bCFFL63qtVYDhFovpUhcotP6p6wmMcaCGj4LStY9n8veyZYegY3U5pQNk2zQRK', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='3Nn3M8', max_length=6),
        ),
    ]
