# Generated by Django 3.2.7 on 2022-06-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0045_auto_20220614_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='4LYRHkEh5r2J33NfVJzgXXKwBPQcFmgtYkSRgT4gqmKHpGZ9QteSocCkWpBXe9oa', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='3wViUK', max_length=6),
        ),
    ]
