# Generated by Django 3.2.7 on 2022-06-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0044_merge_20220610_1838'),
        ('usuario', '0046_auto_20220614_0232'),
    ]

    operations = [
    ]
