# Generated by Django 3.2.7 on 2022-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0047_merge_20220621_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='FSU9XdwRnDmcnZbe5XJ4Sy9Gzv7HrWHNCNC37GAZ8SWhduWTm6gmiSqw7azkye5H', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='4F4N3s', max_length=6),
        ),
    ]
