# Generated by Django 3.2.7 on 2022-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0048_auto_20220621_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ref',
            field=models.CharField(default='R7m3SHB4ZS28bHSXuq2BUVRqD3FjjFHtbcLEMGjxUwQrQwcC9LBGiuBnJWWdxNuk', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='45QXHo', max_length=6),
        ),
    ]
