# Generated by Django 3.2.7 on 2022-05-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('tiempoInicio', models.CharField(max_length=30)),
                ('tiempoFin', models.CharField(max_length=30)),
                ('tiempoTotalResolucionEjercitario', models.PositiveIntegerField(default=0)),
                ('fechaDeActividad', models.DateTimeField(null=True)),
                ('totalRespuestasCorrectasIngresadasParticipante', models.PositiveIntegerField(default=0)),
                ('numeroTotalDeRespuestasContestadasPorElParticipante', models.PositiveIntegerField(default=0)),
                ('numeroTotalDePreguntasDelEjercitario', models.PositiveIntegerField(default=0)),
                ('calificacionActividad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fechaComentario', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDiscapacidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscapacidadParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradoDeDiscapacidad', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeEjercitario', models.PositiveIntegerField(default=0, unique=True)),
                ('tipoDeEjercitario', models.CharField(max_length=30)),
                ('nombreDeEjercitario', models.CharField(max_length=256)),
                ('instruccionPrincipalEjercitario', models.TextField()),
                ('duracionEjercitarioPorMinutos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('instruccionesParticipantes', models.TextField()),
                ('urlEjercitarios', models.URLField()),
                ('nivel', models.CharField(blank=True, choices=[('Nivel1', 'Nivel 1'), ('NIvel2', 'NIvel 2'), ('NIvel3', 'NIvel 3')], max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaLaboral', models.CharField(blank=True, max_length=50, null=True)),
                ('aniosDeExperiencia', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sectorEconomico', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPregunta', models.PositiveIntegerField(default=0)),
                ('respuestaIngresada', models.CharField(max_length=100)),
                ('tiempoRespuesta', models.CharField(max_length=100)),
                ('preguntaDeLaActividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreguntaDeActividad', to='SimuladoresLaboralesApi.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=300)),
                ('respuestaCorrecta', models.CharField(max_length=100)),
                ('numeroPregunta', models.PositiveIntegerField(default=0)),
                ('preguntaDelEjercitario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreguntaDeEjercitario', to='SimuladoresLaboralesApi.ejercitario')),
            ],
        ),
    ]
