# Generated by Django 3.2.7 on 2021-11-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('tiempoInicio', models.CharField(max_length=30)),
                ('tiempoFin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercitario',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('numeroDeEjercitario', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tipoDeEjercitario', models.CharField(max_length=30)),
                ('nombreDeEjercitario', models.CharField(max_length=30)),
                ('instruccionPrincipalEjercitario', models.CharField(max_length=300)),
                ('principalCompetenciasEjercitario', models.CharField(max_length=100)),
                ('duracionEjercitarioPorMinutos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('instruccionesParticipantes', models.CharField(max_length=300)),
                ('urlEjercitarios', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('nivelDeFormacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('gradoDeDiscapacidad', models.PositiveIntegerField(default=0, null=True)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('carreraUniversitaria', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=15, null=True)),
                ('numeroDeHijos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=30, null=True)),
                ('etnia', models.CharField(blank=True, max_length=30, null=True)),
                ('estudiosPrevios', models.CharField(blank=True, max_length=100, null=True)),
                ('codigoEstudiante', models.CharField(blank=True, max_length=30, null=True)),
                ('nivelDeFormacion', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimuladoresLaboralesApi.evaluador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idSesion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSesion', models.DateTimeField(auto_now=True)),
                ('sesionDelParticipante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimuladoresLaboralesApi.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=300)),
                ('respuesta', models.CharField(max_length=100)),
                ('respuestaObtenida', models.CharField(max_length=100)),
                ('tiempoRespuesta', models.CharField(max_length=100)),
                ('preguntaDeLaActividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimuladoresLaboralesApi.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idExperienciaLaboral', models.AutoField(primary_key=True, serialize=False)),
                ('areaLaboral', models.CharField(blank=True, max_length=50, null=True)),
                ('aniosDeExperiencia', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sectorEconomico', models.CharField(blank=True, max_length=50, null=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimuladoresLaboralesApi.participante')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='ActividadPorEjercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimuladoresLaboralesApi.ejercitario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='sesionPorActividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimuladoresLaboralesApi.sesion'),
        ),
    ]
