# Generated by Django 3.2.7 on 2022-05-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('tiempoInicio', models.CharField(max_length=30)),
                ('tiempoFin', models.CharField(max_length=30)),
                ('tiempoTotalResolucionEjercitario', models.PositiveIntegerField(default=0)),
                ('fechaDeActividad', models.DateTimeField(null=True)),
                ('totalRespuestasCorrectasIngresadasParticipante', models.PositiveIntegerField(default=0)),
                ('numeroTotalDeRespuestasContestadasPorElParticipante', models.PositiveIntegerField(default=0)),
                ('numeroTotalDePreguntasDelEjercitario', models.PositiveIntegerField(default=0)),
                ('calificacionActividad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('idCompetencia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('idDiscapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDiscapacidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercitario',
            fields=[
                ('idEjercitario', models.AutoField(primary_key=True, serialize=False)),
                ('numeroDeEjercitario', models.PositiveIntegerField(default=0, unique=True)),
                ('tipoDeEjercitario', models.CharField(max_length=30)),
                ('nombreDeEjercitario', models.CharField(max_length=256)),
                ('instruccionPrincipalEjercitario', models.TextField()),
                ('principalCompetenciasEjercitario', models.CharField(blank=True, max_length=50, null=True)),
                ('duracionEjercitarioPorMinutos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('instruccionesParticipantes', models.TextField()),
                ('urlEjercitarios', models.URLField()),
                ('nivel', models.CharField(blank=True, choices=[('Nivel1', 'Nivel 1'), ('NIvel2', 'NIvel 2'), ('NIvel3', 'NIvel 3')], max_length=7, null=True)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Competencia', to='SimuladoresLaboralesApi.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=800)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('LGBT', 'LGBT')], max_length=7, null=True)),
                ('img', models.ImageField(blank=True, max_length=250, null=True, upload_to='profile')),
                ('aprobacion', models.BooleanField(default=False)),
                ('tipoUser', models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='evaluador', max_length=13, null=True)),
                ('nivelDeFormacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPregunta', models.PositiveIntegerField(default=0)),
                ('respuestaIngresada', models.CharField(max_length=100)),
                ('tiempoRespuesta', models.CharField(max_length=100)),
                ('preguntaDeLaActividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreguntaDeActividad', to='SimuladoresLaboralesApi.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=300)),
                ('respuestaCorrecta', models.CharField(max_length=100)),
                ('numeroPregunta', models.PositiveIntegerField(default=0)),
                ('preguntaDelEjercitario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreguntaDeEjercitario', to='SimuladoresLaboralesApi.ejercitario')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=800)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('LGBT', 'LGBT')], max_length=7, null=True)),
                ('img', models.ImageField(blank=True, max_length=250, null=True, upload_to='profile')),
                ('carreraUniversitaria', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroDeHijos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=30, null=True)),
                ('etnia', models.CharField(blank=True, max_length=30, null=True)),
                ('estudiosPrevios', models.CharField(blank=True, max_length=100, null=True)),
                ('codigoEstudiante', models.CharField(blank=True, max_length=30, null=True)),
                ('nivelDeFormacion', models.CharField(blank=True, max_length=50, null=True)),
                ('aceptacionPendianteResponsable', models.CharField(default='faltaAceptacion', max_length=100)),
                ('tipoUser', models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='admin', max_length=13, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimuladoresLaboralesApi.evaluador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idExperienciaLaboral', models.AutoField(primary_key=True, serialize=False)),
                ('areaLaboral', models.CharField(blank=True, max_length=50, null=True)),
                ('aniosDeExperiencia', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sectorEconomico', models.CharField(blank=True, max_length=50, null=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperienciaParticipante', to='SimuladoresLaboralesApi.participante')),
            ],
        ),
        migrations.CreateModel(
            name='DiscapacidadParticipante',
            fields=[
                ('idGradoDeDiscapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('gradoDeDiscapacidad', models.PositiveIntegerField(default=0, null=True)),
                ('discapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoDiscapacidad', to='SimuladoresLaboralesApi.discapacidad')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiscapacidadParticipante', to='SimuladoresLaboralesApi.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fechaComentario', models.DateTimeField(null=True)),
                ('comentarioActividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComentarioDeActividad', to='SimuladoresLaboralesApi.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('idAsignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAsignacion', models.DateTimeField(null=True)),
                ('ejercitario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AsignacionEjercitario', to='SimuladoresLaboralesApi.ejercitario')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AsignacionEvaluador', to='SimuladoresLaboralesApi.evaluador')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AsignacionParticipante', to='SimuladoresLaboralesApi.participante')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='ActividadDeParticipante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActividadDelParticipante', to='SimuladoresLaboralesApi.participante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ActividadPorEjercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActividadEjercitarioID', to='SimuladoresLaboralesApi.ejercitario'),
        ),
    ]
