# Generated by Django 3.2.7 on 2022-05-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='tipoUser',
            field=models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='participante', max_length=13, null=True),
        ),
    ]
