# Generated by Django 3.2.7 on 2021-12-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0002_auto_20211217_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ActividadPorEjercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActividadEjercitarioID', to='SimuladoresLaboralesApi.ejercitario'),
        ),
    ]
