# Generated by Django 3.2.7 on 2022-05-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220509_1111'),
        ('SimuladoresLaboralesApi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ActividadDeParticipante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActividadDelParticipante', to='usuario.participante'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AsignacionEvaluador', to='usuario.evaluador'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AsignacionParticipante', to='usuario.participante'),
        ),
        migrations.AlterField(
            model_name='discapacidadparticipante',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiscapacidadParticipante', to='usuario.participante'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperienciaParticipante', to='usuario.participante'),
        ),
    ]
