# Generated by Django 3.2.7 on 2021-12-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0003_alter_actividad_actividadporejercitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fechaAsignacion',
            field=models.DateTimeField(null=True),
        ),
    ]
