# Generated by Django 3.2.7 on 2022-05-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0003_auto_20220509_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercitario',
            name='numeroDeEjercitario',
        ),
        migrations.AddField(
            model_name='ejercitario',
            name='variaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
