# Generated by Django 3.2.7 on 2022-01-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0004_alter_asignacion_fechaasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='password',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='password',
            field=models.CharField(max_length=800),
        ),
    ]
