# Generated by Django 3.2.7 on 2022-05-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0005_auto_20220510_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='actividadPorEjercitario',
            new_name='actividadEjercitario',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='actividadDeParticipante',
            new_name='actividadParticipante',
        ),
    ]
