# Generated by Django 3.2.7 on 2022-05-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20220510_1045'),
        ('SimuladoresLaboralesApi', '0006_auto_20220510_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='actividadEjercitario',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='actividadParticipante',
        ),
        migrations.AddField(
            model_name='actividad',
            name='ejercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercitario', to='SimuladoresLaboralesApi.ejercitario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='usuario.participante'),
        ),
    ]
