# Generated by Django 3.2.7 on 2022-01-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0007_auto_20220106_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
