# Generated by Django 3.2.7 on 2022-05-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20220511_0924'),
        ('SimuladoresLaboralesApi', '0007_auto_20220510_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidadparticipante',
            name='discapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_discapacidad', to='SimuladoresLaboralesApi.discapacidad'),
        ),
        migrations.AlterField(
            model_name='discapacidadparticipante',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discapacidad_participante', to='usuario.participante'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_participante', to='usuario.participante'),
        ),
    ]
