# Generated by Django 3.2.7 on 2022-05-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20220511_0936'),
        ('SimuladoresLaboralesApi', '0008_auto_20220511_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidadparticipante',
            name='discapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoDiscapacidad', to='SimuladoresLaboralesApi.discapacidad'),
        ),
        migrations.AlterField(
            model_name='discapacidadparticipante',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiscapacidadParticipante', to='usuario.participante'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperienciaParticipante', to='usuario.participante'),
        ),
    ]
