# Generated by Django 3.2.7 on 2022-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0008_auto_20220106_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='idActividad',
            new_name='idPregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='numeroPregunta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuestaObtenida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tiempoRespuesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
