# Generated by Django 3.2.7 on 2022-05-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0009_auto_20220511_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='calificacionActividad',
            new_name='PreguntasContestadas',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='numeroTotalDePreguntasDelEjercitario',
            new_name='calificacion',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='fechaDeActividad',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='numeroTotalDeRespuestasContestadasPorElParticipante',
            new_name='preguntasCorrectas',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='tiempoTotalResolucionEjercitario',
            new_name='tiempoTotal',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='totalRespuestasCorrectasIngresadasParticipante',
            new_name='totalPreguntas',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='ejercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencia', to='SimuladoresLaboralesApi.competencia'),
        ),
    ]
