# Generated by Django 3.2.7 on 2022-01-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0009_auto_20220106_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='respuesta',
            new_name='respuestaCorrecta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='preguntaDeLaActividad',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuestaObtenida',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tiempoRespuesta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='preguntaDelEjercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreguntaDeEjercitario', to='SimuladoresLaboralesApi.ejercitario'),
        ),
        migrations.AlterField(
            model_name='ejercitario',
            name='numeroDeEjercitario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPregunta', models.PositiveIntegerField(default=0)),
                ('respuestaIngresada', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempoRespuesta', models.CharField(blank=True, max_length=100, null=True)),
                ('preguntaDeLaActividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreguntaDeActividad', to='SimuladoresLaboralesApi.actividad')),
            ],
        ),
    ]
