# Generated by Django 3.2.7 on 2022-05-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20220512_0928'),
        ('SimuladoresLaboralesApi', '0010_auto_20220512_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercitario',
            old_name='duracionEjercitarioPorMinutos',
            new_name='duracion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentarioActividad',
        ),
        migrations.AddField(
            model_name='comentario',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario_actividad', to='SimuladoresLaboralesApi.actividad'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario_evaluador', to='usuario.evaluador'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario_participante', to='usuario.participante'),
        ),
        migrations.AddField(
            model_name='ejercitario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Nivel1', 'Nivel 1'), ('NIvel2', 'NIvel 2'), ('NIvel3', 'NIvel 3')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ejercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_ejercitario', to='SimuladoresLaboralesApi.ejercitario'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_participante', to='usuario.participante'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='ejercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_competencia', to='SimuladoresLaboralesApi.competencia'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='preguntaDelEjercitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntaDeEjercitario', to='SimuladoresLaboralesApi.ejercitario'),
        ),
    ]
