# Generated by Django 3.2.7 on 2022-01-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0010_auto_20220107_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='respuestaIngresada',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='tiempoRespuesta',
            field=models.CharField(max_length=100),
        ),
    ]
