# Generated by Django 3.2.7 on 2022-05-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0011_auto_20220512_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='ejercitario',
            new_name='competencia',
        ),
    ]
