# Generated by Django 3.2.7 on 2022-01-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0012_alter_ejercitario_instruccionesparticipantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('idDiscapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDiscapacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('gradoDeDiscapacidad', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participante',
            name='gradoDeDiscapacidad',
        ),
        migrations.AddField(
            model_name='participante',
            name='discapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiscapacidadParticipante', to='SimuladoresLaboralesApi.discapacidad'),
        ),
    ]
