# Generated by Django 3.2.7 on 2022-01-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0013_auto_20220113_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discapacidad',
            name='gradoDeDiscapacidad',
        ),
        migrations.AddField(
            model_name='participante',
            name='gradoDeDiscapacidad',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
