# Generated by Django 3.2.7 on 2022-01-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0014_auto_20220113_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidad',
            name='tipoDiscapacidad',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
