# Generated by Django 3.2.7 on 2022-05-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0014_rename_preguntascontestadas_actividad_preguntascontestadas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
