# Generated by Django 3.2.7 on 2022-05-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0016_auto_20220513_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercitario',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencia_ejercitario', to='SimuladoresLaboralesApi.competencia'),
        ),
    ]
