# Generated by Django 3.2.7 on 2022-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0019_alter_comentario_fechacomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaComentario',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
