# Generated by Django 3.2.7 on 2022-01-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0019_auto_20220113_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='estado',
            field=models.CharField(default='activo', max_length=100),
        ),
        migrations.AddField(
            model_name='participante',
            name='estado',
            field=models.CharField(default='activo', max_length=100),
        ),
    ]
