# Generated by Django 3.2.7 on 2022-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0020_auto_20220120_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='calificacionActividad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actividad',
            name='numeorTotalDeRespuestasDelEjercitario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actividad',
            name='totalRespuestasCorrectasIngresadasParticipante',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
