# Generated by Django 3.2.7 on 2022-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0021_actividad_calificacionporcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tiempoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
