# Generated by Django 3.2.7 on 2022-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0021_auto_20220120_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='numeorTotalDeRespuestasDelEjercitario',
            new_name='numeroTotalDePreguntasDelEjercitario',
        ),
        migrations.AddField(
            model_name='actividad',
            name='numeroTotalDeRespuestasContestadasPorElParticipante',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
