# Generated by Django 3.2.7 on 2022-01-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0022_auto_20220120_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tiempoTotalResolucionEjercitario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
