# Generated by Django 3.2.7 on 2022-05-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0022_alter_actividad_tiempototal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='calificacionPorcentaje',
        ),
    ]
