# Generated by Django 3.2.7 on 2022-01-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0023_actividad_tiempototalresolucionejercitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercitario',
            name='numeroDeEjercitario',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
