# Generated by Django 3.2.7 on 2022-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0023_remove_actividad_calificacionporcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='discapacidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
