# Generated by Django 3.2.7 on 2022-01-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0024_alter_ejercitario_numerodeejercitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='aceptacionPendianteResponsable',
            field=models.CharField(default='faltaAceptacion', max_length=100),
        ),
    ]
