# Generated by Django 3.2.7 on 2022-06-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0040_auto_20220603_1205'),
        ('SimuladoresLaboralesApi', '0024_rubrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencia_certificado', to='SimuladoresLaboralesApi.competencia')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participante_certificado', to='usuario.participante')),
            ],
        ),
    ]
