# Generated by Django 3.2.7 on 2022-06-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0024_discapacidad_descripcion'),
        ('SimuladoresLaboralesApi', '0025_certificado'),
    ]

    operations = [
    ]
