# Generated by Django 3.2.7 on 2022-02-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0025_participante_aceptacionpendianteresponsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=1000)),
                ('comentarioActividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComentarioDeActividad', to='SimuladoresLaboralesApi.actividad')),
            ],
        ),
    ]
