# Generated by Django 3.2.7 on 2022-02-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0027_comentario_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fechaComentario',
        ),
    ]
