# Generated by Django 3.2.7 on 2022-02-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimuladoresLaboralesApi', '0030_remove_user_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
